# Generated by Django 4.0.6 on 2022-07-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_city', models.CharField(max_length=50)),
                ('address_street_name', models.CharField(max_length=100)),
                ('address_house_number', models.CharField(max_length=10)),
                ('address_zipcode', models.CharField(max_length=6)),
                ('dms_id', models.IntegerField(blank=True, null=True)),
                ('paid_contribution', models.BooleanField(default=False)),
            ],
        ),
    ]
