# Generated by Django 4.0.6 on 2022-07-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chairs_committees', to='members.member')),
                ('members', models.ManyToManyField(related_name='in_committees', to='members.member')),
            ],
        ),
    ]
